src/Entity/ImageFile.php
<?php

namespace App\Entity;

use App\Repository\ImageFileRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Service\UploaderHelper;
use App\Service\UploadHelper;

/**
 * @ORM\Entity(repositoryClass=ImageFileRepository::class)
 */
class ImageFile
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pathName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getPathName(): ?string
    {
        return $this->pathName;
    }

    public function setPathName(string $pathName): self
    {
        $this->pathName = $pathName;

        return $this;
    }

    public function getImagePath()
    {
        return UploadHelper::IMAGE_PATH.'/'.$this->getPathName();
    }
}

src/Controller/ListController.php
<?php

namespace App\Controller;

use App\Repository\ImageFileRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ListController extends AbstractController
{
    /**
     * @Route("/list", name="list")
     */
    public function index(Request $request, ImageFileRepository $repository)
    {
        $q = $request->query->get('q');
        $images = $repository->searchByFullTextColumn($q);


        return $this->render('list/index.html.twig', [
            'images' => $images,
        ]);
    }
}

templates/list/index.html.twig
{% extends 'base.html.twig' %} {% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card bg-light mb-3 mt-3">
                <form>
                    <div class="d-flex">
                        <input type="text"
                            name="q"
                            class="form-control"
                            value="{{ app.request.query.get('q') }}"
                            placeholder="Search..."
                        >
                        <button type="submit" class="btn btn-outline-primary">
                            Search
                        </button>
                    </div>
                </form>
                <div class="card-header">List of Images</div>
                <div class="card-body">
                    <div class="row">
                        {% for image in images %}
                            <div class="col-12 col-lg-6 col-xl-4">
                                <img class="img-size" src="{{ uploaded_asset(image.imagePath) }}">
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}